In [2]:
#numpy
#create numpy array
#num py in 1D array
import numpy as np
arr = np.array([1,3,4,5])
print(arr)
print(type(arr)

[1 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#numpy in 2D array 
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
#numpy in 3D array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#check number of dimensions
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
#ndim is use to check dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
#create dimensions using numpy
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [13]:
#expirement
import numpy as np
arr = (45)
FourD = np.array(arr, ndmin = 4)
print(FourD)

[[[[4 5]]]]


In [3]:
#dimensions in numpy
import numpy as np
arr = np.array([[1, 2, 3,], [3, 4, 5]])
print(arr.ndim)



2


In [6]:
#broadcasting in numpy
#Broadcasting ka matlab hai ke jab aap NumPy mein do arrays ke beech operation
#karte hain, to agar unki shapes (size) alag ho, to NumPy un arrays ko aapas 
#mein match kar leta hai. Is tarah se, aapko arrays ko manually resize nahi karna padta.
#for example
import numpy as np
arr = np.array([1,2,3])
result = arr+5
print(result)

#or 
arr2 = np.array([[1],[2],[3]])
arr3 = np.array([10,20,30])
resultt = arr2 + arr3
print(resultt)

[6 7 8]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [7]:
#shape in numpy
#shape
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)

#or 
#data means cols,, and [] means rows
arr1 = np.array([[42,42],[42,42]])
print(arr1.shape)

(3, 3)
(2, 2)


In [8]:
#index calling 
arr = np.array([1,2,3,4])
print(arr[-2])


3
